[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
deadpool-diesel = { workspace = true }
diesel = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
